spring.application.name=assignment

spring.datasource.url=jdbc:postgresql://localhost:5432/bitespeed
spring.datasource.username=postgres
spring.datasource.password=Moinu2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
